### ISSUE TITLE
Clciking anywhere in the member card should open up the member profile page

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#111]
Currently, only when we click on the members image, then only we are being redirected to the member profile page

![image](https://user-images.githubusercontent.com/29303618/106822269-d76f5700-66a4-11eb-8777-e362f01cb23d.png)

Change this process, so that clicking anywhere on the members card should open his profile page.

![image](https://user-images.githubusercontent.com/29303618/106822366-084f8c00-66a5-11eb-985d-fb3f163eb558.png)

**Comment by sanyogita14** [comment]
Can I work on this issue?
