### ISSUE TITLE
Contributions container design fix

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#136]
We need to do 2 things here

1. Add sliding animation when we click on the arrows here

![image](https://user-images.githubusercontent.com/29303618/109544074-1f8b6900-7aed-11eb-9606-e195bd16abd7.png)

2. The width of the contributions container changes with the amount of data, this needs to be fixed

Before

![image](https://user-images.githubusercontent.com/29303618/109544281-5eb9ba00-7aed-11eb-95af-e973d820069d.png)

After we expand the contributions

![image](https://user-images.githubusercontent.com/29303618/109544348-72652080-7aed-11eb-87fa-dd16ada71a82.png)

The layout shifts

**Comment by TD-17** [comment]
Please assign this one to me

**Comment by sumitd94** [comment]
> Please assign this one to me

Done
