### ISSUE TITLE
Members Card UI Improvement

### ISSUE THREAD

**Issue by PremanandChowdhury** [Real-Dev-Squad/website-members#142]
### Member cards With Width 
![member-profile_card_with_width](https://user-images.githubusercontent.com/26891223/111151075-fa9af980-85b4-11eb-952b-49b4b7e01a16.png)

### Member cards Without Width 
![members-profile_card_without_width](https://user-images.githubusercontent.com/26891223/111151148-143c4100-85b5-11eb-8d14-8ea7e2890a95.png)

**Comment by ptechofficial** [comment]
How exactly do you want the designs?
@PremanandChowdhury

**Comment by PremanandChowdhury** [comment]
Like the image without the width @ptechofficial 
IDK whether this is resolved or not 🤔

**Comment by imaxisXD** [comment]
resolved or not ?

**Comment by PremanandChowdhury** [comment]
> resolved or not ?

Yes, it id Resolved.
