### ISSUE TITLE
Contribution UI for Member details page

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-members#152]
Design: [Figma Link](https://www.figma.com/file/2esJpmIIa0BzbM9QOWMgXd/PR-design?node-id=0%3A1)

**Comment by iRahulP** [comment]
Hi @ankushdharkar,
The issue requires an update in the UI for the Members contribution component as the layout somehow similar to the one provided in Figma link right?
![Screenshot from 2021-03-27 22-37-34](https://user-images.githubusercontent.com/26308074/112728418-3470e600-8f4d-11eb-8a37-4a76db9992c0.png)

So, Does it require creation of a new component or updating existing component with UI change and additional information?

**Comment by iRahulP** [comment]
Hi @ankushdharkar,
I tried to change the design a bit and also added the current Pull Request with respect to each contribution.
Please refer the snap as a result after a few changes:
![Screenshot from 2021-03-27 23-36-23](https://user-images.githubusercontent.com/26308074/112730097-9fbeb600-8f55-11eb-8bd7-e6de011d1b3c.png)

Also,Can I start working on this issue?
cc : @sumitd94

**Comment by ankushdharkar** [comment]
@iRahulP 

> Does it require creation of a new component or updating existing component with UI change and additional information?

What would you recommend?

**Comment by iRahulP** [comment]
@ankushdharkar
1) I Think the current design of the contributions can be updated as per the PR design from the figma link as contributions are specifc to Member, and also there can be additional data which can be added.

2) Another way can be to create a completely new Page which can have contributions from all the Members which will not be specific to Profile Page.

As of now I think updating the existing component with UI change and additional information from PR data as per figma link can be done.
@sumitd94 - Could you suggest me if I can start with redesign of existing component.

**Comment by sumitd94** [comment]
#157
