### ISSUE TITLE
Show progress indicators of the active task

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-members#161]
Design:[ Figma Link](https://www.figma.com/file/3KGNxBI82KfBhEwSU2LXsg/Progress-of-task?node-id=0%3A1)

We want to show how far along is the currently active task

- If the percentage of days remaining >= percentage of a task left, the color for **both** indicators is green
-   If percentage of days remaining < 50%  and percentage of task left > 75%, orange 
-  If the percentage of days remaining < 25% percentage of a task left > 35%, the color for both indicators is red  
- Else yellow

E.g The example task in the design was estimated to take 14 days total. The deadline to complete is 8 days away, but the progress states it’s more than 60% done. So, it’s green

**Comment by KhushalAbrol** [comment]
Plz assign me this task

**Comment by Pujarini** [comment]
Reopening the issue to fix yellow color

**Comment by Pujarini** [comment]
![image](https://user-images.githubusercontent.com/34391629/132894894-9f10ffe3-7268-4b3b-a231-ddebb0e790c1.png)
@sumitd94 let me know if this shade for yellow looks okay.
