### ISSUE TITLE
Search / Sort members on parameters

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-members#164]
We want to sort users:

- Alphabetically (First name)
- Based on skills: 'NodeJS', 'ReactJS', 'JS'
- Based on accomplishments levels: 'Send proper PRs', 'Code reviewer', 'Conducted KT session', 'Leader', 'Feature Owner', etc
- Based on recently active in tasks
- Open to new roles

**Comment by sebuelias** [comment]
Can I try pick this one up?

**Comment by sebuelias** [comment]
Hey @ankushdharkar 
Can I pick this task up?

**Comment by sebuelias** [comment]
> We want to sort users:
> 
> * Alphabetically (First name)
> * Based on skills: 'NodeJS', 'ReactJS', 'JS'
> * Based on accomplishments levels: 'Send proper PRs', 'Code reviewer', 'Conducted KT session', 'Leader', 'Feature Owner', etc
> * Based on recently active in tasks
> * Open to new roles

By sort user on the basis of above, you meant filter I suppose?
Also, do we have a design style of the input box we can use search using FirstName LastName?
For the above filter, do we handle using a drop-down?
Also, I wasn't able to get the Skills, accomplishments, recent activities in the member object, do we have any other ways of obtaining the same?
