### ISSUE TITLE
Create a generic re-usable modal

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#193]
Create a generic re-usable modal that can be used anywhere on the member's site.

Here are the requirements

- [ ] should be mobile responsive
- [ ] should contain a backdrop, upon clicking should close the modal
- [ ] the backdrop color can be dynamic and should depend on the prop we pass. we should be able to choose the color of the backdrop as per what we want by passing the prop.

Implement this by creating a new `NextJS App`

**Comment by PremanandChowdhury** [comment]
Ok, I will be working on it.

**Comment by sumitd94** [comment]
#237
