### ISSUE TITLE
Add some top and bottom margin around the footer

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#196]
Currently, the footer content is stuck to the bottom of the screen

![image](https://user-images.githubusercontent.com/29303618/123820665-614fe300-d918-11eb-924e-182c8b2235c3.png)

we need to add some margin around it.
Add it for both the home page and the member-profile details page as well (click on the member card and it will redirect you the profile detail page)

**Comment by shubhamdsm** [comment]
Can I take this issue?

**Comment by sumitd94** [comment]
> Can I take this issue?

Hey Shubham, Sorry! An existing member of RDS has already taken this task.
But don't worry, we have many more tasks which you can take up. Why not be a part of RDS and explore all by yourself? ;)

Let me know if you would like to be a part of it and I will send across the invite to you :)

**Comment by shubhamdsm** [comment]
Actually I am in the RDS discord channel.

**Comment by rohandhar1234** [comment]
please assign me this task

**Comment by sumitd94** [comment]
#202
