### ISSUE TITLE
New members section enhancement

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#218]
We need to do 2 changes to the new member's section

- [x] Remove the borders from each member card (new-member)
- [x] The right and left spacing in the new-members section should be same as it is for the Main members section. Currently the new-members section takes up almost the entire screen. So let's make sure we have both the section aligned equally.

**Comment by rohandhar1234** [comment]
Can I take this task?

**Comment by sumitd94** [comment]
#221
