### ISSUE TITLE
make the profile overview section of the page sticky to the page.

### ISSUE THREAD

**Issue by thoughtlessmind** [Real-Dev-Squad/website-members#220]
currently the profile overview section scrolls with the page. Make that section sticky to the page.

![image](https://user-images.githubusercontent.com/51883613/128627635-4d505eeb-1578-495e-90ce-93e7add6bd30.png)

after scrolling 

![image](https://user-images.githubusercontent.com/51883613/128627683-f671b892-d98a-4738-ba4e-8dddde6d05f4.png)

make that section persistent to top after scrolling

**Comment by singh3069** [comment]
I want to pick up this issue, can you please assign this to me.
