### ISSUE TITLE
create a base layout 

### ISSUE THREAD

**Issue by shihabus** [Real-Dev-Squad/website-members#29]
We should have a base page layout that will be used by all the pages. This will be the topmost container for all pages/components.

**Comment by manjots1607** [comment]
Should I do this.....???

**Comment by shihabus** [comment]
great if you can @manjots1607

**Comment by manjots1607** [comment]
@shihabus I checked this and found that we already have one, i.e _app.js component which works as layout component and I feel No Need of specialized Layout Component because that will be redundant. Can you help me in this and clarifying needs??

**Comment by ankushdharkar** [comment]
I agree @manjots1607. Please confirm @shihabus and close this issue. Thanks guys

**Comment by Shihab-Duzno** [comment]
@manjots1607 if styling could fix it, then no issues. we can close this.
