### ISSUE TITLE
[ESLint Warnings] Remove all the warnings

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#294]
Right now whenever we raise a PR, there is a lot of warning we see by ESlint in the PR.
We need to fix all those warnings

example PR for reference - https://github.com/Real-Dev-Squad/website-members/pull/291/files

If you scroll down, you will see all the warnings.

<img width="1408" alt="Screenshot 2022-01-02 at 1 09 48 PM" src="https://user-images.githubusercontent.com/29303618/147869344-1392815c-4b73-43a8-a199-94f44ab0ac9e.png">

**Comment by Debarshi95** [comment]
Hey @sumitd94 , I would like to work on this one. Can you assign??
