### ISSUE TITLE
Standardize RDS logo size.

### ISSUE THREAD

**Issue by Kshashank99** [Real-Dev-Squad/website-members#304]
## 1. Dimension of RDS logo on the main page of different sites is non-uniform in desktop and mobile view.
for eg.
### Home 
![image](https://user-images.githubusercontent.com/64394213/148959459-12ec576f-cfd1-4070-9f9f-df5f56c61c11.png)
### Members 
![image](https://user-images.githubusercontent.com/64394213/148959652-41ce47c0-1948-4d23-b6ad-a8f53fd1b655.png)
and so on.
## 2. Discuss the issue with the design team (@palakgupta2712) and decide the final dimension of logo in Mobile and desktop view of the member site.
Reach out to me and @palakgupta2712 in case of any blocker.

**Comment by priyanshk20** [comment]
Please assign it to me.

**Comment by Kshashank99** [comment]
Assigned.

**Comment by palakgupta2712** [comment]
- Apply the following CSS to the logo in mobile view
` width: 200px;
 height: 200px;
`
