### ISSUE TITLE
Members Profile data not showing up

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#306]
For some members we are not able to see their data on their profile page.

example - https://members.realdevsquad.com/lakshay

![Screenshot 2022-01-14 at 11 11 23 AM](https://user-images.githubusercontent.com/29303618/149457666-f2660960-8365-4d7e-914c-b4535c2c770e.png)

**Comment by shubham-y** [comment]
I would like to work on this issue
