### ISSUE TITLE
[New Members] Do not fetch images from github static repo

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-members#311]
Right now we are trying to fetch images for all the members (including new members) from this static repo - https://github.com/Real-Dev-Squad/website-static

New members do not have their images in this repo and due to this, we are getting 404 errors in the console.

![Screenshot 2022-01-15 at 4 01 16 PM](https://user-images.githubusercontent.com/29303618/149618596-63d0180f-e91a-46e1-ac91-da63200e4648.png)

For new members we should not be fetching images at all and just display avatar.

**Comment by abhay05** [comment]
Pls assign it to me

**Comment by abhay05** [comment]
#314
