### ISSUE TITLE
Fix the login issue in navbar

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-members#316]
Issue for the fix
- Issue #261 
- PR #265 
**Bugs Encountered**
- `/users/self` call giving 404
![image](https://user-images.githubusercontent.com/78433013/150922111-f91b77db-03c5-4dac-8283-657339db1a77.png)

**Comment by Kshashank99** [comment]
Did this issue after merging my last PR?

**Comment by rohan09-raj** [comment]
> Did this issue appeared after merging my last PR? How did you check it. Have you set up staging development for it already

I have taken the pull from your branch and was testing out your code there I saw this issue.
