### ISSUE TITLE
Get every members to upload there profile picture in https://my.realdevsquad.com/profile?dev=true (last date : 25th Feb, 2022)

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-members#333]
## Members who updated their profile pictures
https://my.realdevsquad.com/profile?dev=true
Updates here is delayed by 1-3 days

- [x] Akshay Shinde
- [x] Aman Saxena
- [x] Aman Anand
- [ ] Ankita Bannore
- [ ] Ankur Narkhede
- [x] Ankush Dharkar
- [ ] Anhwini Pawar
- [ ] Bhavesh Khandelwal
- [x] Deipayan Dash
- [ ] Devashish
- [x] Harshith Venkatesh
- [x] Ishika Baid
- [x] Lakshay Manchanda
- [x] Mehul Chaudhari
- [ ] Moses Kamara
- [x] Nikhil Bhandarkar
- [x] Pavan Bhat
- [x] Prakash Choudhary
- [ ] Pranav Gajjewar 
- [x] Premanand Chowdhury
- [ ] Pujarini Jena
- [ ] Rahil Kapoor
- [x] Raja Kvk
- [x] Rohan Raj Gupta
- [x] Rohit Kuwar
- [x] Rucha Patil
- [ ] Sagar Bajpai
- [ ] Sai Shankar Manugula
- [ ] Sanyogita Tilak
- [x] Shashwat Bagaria 
- [x] Shubham Yadav
- [x] Sumit Dhanania
- [x] Swaraj Rajpure
- [ ] Swebert Correa
- [ ] Tanya Dixit
- [ ] Vividh Bhardwaj

**Comment by Bibek13yadav** [comment]
Hello 👋
