### ISSUE TITLE
BUG: Archive feature is not working

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-members#337]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1935403/159926707-1fad013e-d41c-4baf-9bde-a7de040e057d.png">

**Comment by Chaitanya7666** [comment]
@ankushdharkar I would like to take it up. Could you please assign this issue to me and give me more information on how to reproduce this issue? 

**Note:** I tried to reproduce the issue. I was not able to figure it out.

**Comment by vinayak-trivedi** [comment]
closing this as PR for this is merged
