### ISSUE TITLE
BUG: Broken Social Media Link

### ISSUE THREAD

**Issue by shubham-y** [Real-Dev-Squad/website-members#386]
The Twitter profile links of all the members are broken.

Steps to reproduce: Goto to [members](https://members.realdevsquad.com/) page and click any members Twitter profile link.

**Comment by poonammohata** [comment]
@shubham-y I would like to take this issue

**Comment by shubham-y** [comment]
> @shubham-y I would like to take this issue
Done! Assigned it to you. Please do let me know the ETA

**Comment by foobar41** [comment]
Hi @shubham-y, can I work on this issue?
