### ISSUE TITLE
add link to the members page in README

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-members#45]
This is a beginner issue, kindly keep this for a newcomer, so that they can make their first PR for RDS!

What are you expected to do?
- Edit README.md and add link to https://members.realdevsquad.com/ under the first title.

Hope you have fun at RDS!

**Comment by Rucha1499** [comment]
I would like to work on this isssue.  Can please assign it to me ?

**Comment by akankshadharkar** [comment]
@Rucha1499 done
