### ISSUE TITLE
blur the screen when modal is opened

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/website-members#451]
when a superuser wants to move a user to a member or if he wants to change the task to noteworthy or change it back to other tasks, then a modal shows up which lets them perform those superuser actions, we should make the background blur when the modal shows up.

images for reference⬇️

![image](https://user-images.githubusercontent.com/90315175/195553560-a819e843-27df-4ea9-bce5-52336db4e3ec.png)

![image](https://user-images.githubusercontent.com/90315175/195553959-651b9569-eaed-4525-a9d8-7891ecad538f.png)

**Comment by kshitij430** [comment]
Hi, Please assign it to me.

**Comment by vinayak-trivedi** [comment]
assigned to you @kshitij430

**Comment by kush-x7** [comment]
Is this task completed now?

**Comment by vinayak-trivedi** [comment]
closing this as it is done
