### ISSUE TITLE
Integrated new Signup Flow

### ISSUE THREAD

**Issue by ivinayakg** [Real-Dev-Squad/website-members#463]
## Issue
When signing in with GitHub send the page href in query params as `&state=`
- RFC - https://github.com/Real-Dev-Squad/website-backend/issues/688

### Description
When you visit the `main site` and click on login, you are redirected to the original GitHub login page. We want to emulate a similar scenario for the `member site`.

### Expected Flow
- User visits `welcome-site` for the first time
- User clicks on `sign-in-with-github`
- Now, they are redirected to the GitHub login page
- once the login is successful the user is expected to land back to the `member site`
- Example PR - https://github.com/Real-Dev-Squad/website-www/pull/277

**Comment by shmbajaj** [comment]
@ivinayakg I want to work on this issue.
cc: @vinayak-trivedi

**Comment by shmbajaj** [comment]
#### RFC
What if make this backend-driven so, TTL for github mock url will be consistent accross web and mobile-web?

cc: @ivinayakg @vinayak-trivedi

**Comment by ivinayakg** [comment]
> #### RFC
> What if make this backend-driven so, TTL for github mock url will be consistent accross web and mobile-web?
> 
> cc: @ivinayakg @vinayak-trivedi 

- elaborate this on a message or a call
- let's just stick to the scope of this task only later on we can find things to do.

**Comment by shmbajaj** [comment]
> let's just stick to the scope of this task only later on we can find things to do.

As of now sticking on the scope of this task.

**Comment by shmbajaj** [comment]
[PR For Integration New Signup Flow](https://github.com/Real-Dev-Squad/website-members/pull/480)

cc: @ivinayakg @vinayak-trivedi
