### ISSUE TITLE
show achievement badges on members site

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/website-members#469]
### What is needed to be done?

- We need to show badges on the user profile page
-  Those badges will determine the achievements of a user in RDS, e.g. when they become a member, a member badge appears on top of their profile, and many other badges can be added based on their performance and achievements
- Currently, we have hardcoded badges on the user/member profile, which appears when we put `dev=true` in the query params
![image](https://user-images.githubusercontent.com/90315175/199052236-b5d358d2-8475-41f1-8876-42fb4fc950be.png)

#### Requirements
- We have an endpoint `/badges` and `/badges/username` which returns all the badges and badges that a user has respectively
- We have to add badges to our database with some other data like what is that particular badge about, who added it, when was it added etc.
- We need to give the superuser an option on the members page using which they can add badges to a particular member/user, also they should be able to create some badges there
- on hovering over those badges it should show all the info about that badge
- If the user is on a mobile phone, they can click on that badge to get info about that badge

**Comment by vinayak-trivedi** [comment]
List of badge images currently existing in cloudinary:

- [trophy](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/007-trophy_d7asne.png) 
- [treasure](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/027-treasure_chest_dyv8hf.png)
- [welcomer](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/011-award_rt83qf.png)
- [medal](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/016-medal_i1nuyk.png)
- [ribbon](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/017-flag_hfx8bn.png)
- [rosette](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/021-award_ivizb3.png)
- [shield](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/019-award_j5hpsn.png)
- [merit](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/023-award_dbia37.png)
- [glory](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/025-award_juwt6i.png)
- [certificate](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/001-certificate_ojcdwm.png)
- [accomplish](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/008-trophy_sotyup.png)
- [speedy](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/026-gold_medal_fayvhv.png)
- [boss](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/028-throne_slrpdh.png)
- [award](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/022-award_gys98n.png)
- [active](https://res.cloudinary.com/realdevsquad/image/upload/v1608763376/badges/025-award_swdg6r.png)

**Comment by shmbajaj** [comment]
@vinayak-trivedi I want to work on this issue.

**Comment by shmbajaj** [comment]
@vinayak-trivedi can you assign this to me...

**Comment by shmbajaj** [comment]
### Doubts

1. Why dev-user/super-user is open to all? `[url/?dev=true]`
2. To determine is user a super-user, will be using query param? (`?dev=true`)
3. Why endpoints `/badges` is returning this response?(is badges info yet to be stored in db)
```javascript
{
    "message": "Badges returned successfully!",
    "badges": [ ]
}
``` 
4. To add badge from web-app what is the endpoint and payload type?
4a. Is super-user allowed to add multiple badges simulatenously from web-app?
4b. How the UI should look like?
```
We have to add badges to our database with some other data like what is 
that particular badge about, who added it, when was it added etc.
```
5. How super-user can create badges: image upload or image url?

---- 

- Assuming member/user badges will be visible to all

cc: @vinayak-trivedi @DashDeipayan

**Comment by vinayak-trivedi** [comment]
1. dev=true is accessible to everyone because we do need to put certain features behind a feature flag and test them and superuser is not open to all
2. we do not use query param to determine if the user is superuser, we make a call to `/self` endpoint in the backend and check if it contains the role `super_user` and set it's value to true in the context
3. because there are no badges in the db
4. we do not have an endpoint to add tags to the db, this also needs to be done by you
5. currently there is no option for superuser to create badges, this will be your task to give them a place to make badges

**Comment by shmbajaj** [comment]
# RFC || Technial Document

## Purpose
- To communicate the technical details of the planned solution to show 
  achievement badges on members-site.
- It is for the members-site AO, PM, Designer, Developer, 
  SuperUser and RDS Users.
- Before reading further go through this issue [469: show-achievements-badge](https://github.com/Real-Dev-Squad/website-members/issues/469)

## Problem
- Superuser cannot assign and unassign badges(token of achievements/performance) to the members
- Superuser cannot add and remove badges.

### More on Problem
- On the members-site member profile page to show member achievement and performance, 
  badges are hardcoded and default for every member.
- Superuser cannot assign/unassign and add/remove badges.
- To measure member achievement and performance, badges are used.

## Requirements
- RDS users, members and superuser can see list of achievements(badges) 
  of a member on the members profile page.
- Superuser can only add and remove badges assignable to member, using members-site.
- Superuser can only assign and unassign badges to member, using members-site.
- Create and Delete badges onto database using API.
- Get list of badges from database using API.
- Show badge info on hovering over the badge, and on mobile-web clicking the badge.

## Success Criteria
- Superuser can add, assign, remove, and unassign badges
- Users can see member badges.

## Component Level Design(WebUI + API calls) 
- ### Assign and Unassign Badges to Members

![Group 12](https://user-images.githubusercontent.com/29247011/201527372-90bbd02e-740f-4cf5-be23-35e48f658c99.png)
<small>Member page badges assigned component</small>

![Group 5](https://user-images.githubusercontent.com/29247011/201527379-4f5e2cd3-0b74-4ad6-a593-875c023c4866.jpg)
`Action Items`
1. On clicking on add button(on member page, visible to Superuser only) Superuser will be shown modal to assign/unassign badges.
2. Input type checkbox will be used to assign/unassign badges
3. On modal close a `POST` request will be made to update member badges (alternative: save button)
4. Search badges filter: frontend task 
5. Hover/Click(on mobile) to show badge info
6. API calls
```javascript
GET /badges (to get list of badges available)
GET /badges/username (to get list of badges assigned to member)
POST /badges/username (to update member badges)
payload: {
badgeIds: string[]
}
```

- ### Add Badges
![Group 10](https://user-images.githubusercontent.com/29247011/201527983-949de7a0-21c8-42ac-9e18-dd204f37f7ca.png)

`Action Items`
1. Drop or Browse to upload badge image
2. Give title and description for the badge
3. [OPTINAL] See badge image upload progress and preview
4. Missing flow of how Superuser will land to add badges component
   (one possible way, add badges button on footer of assign/unassign badges modal)
5. Hover/Click over badge to see badge info
6. API Call
```javascript
POST /badges
payload: {
url: string;
title: string;
description: string;
createdAt: timestamp:
createdBy: string;
}

```

- ### Remove Badges
<img width="518" alt="Group 11" src="https://user-images.githubusercontent.com/29247011/201528135-5db36f13-5a2c-478f-8ab9-4336c9d20af0.png">

`Action Items`
1. Search badges Filter: Frontend task
2. On click on delete badge button, Superuser will be shown confirm dialog/alert [OPTIONAL]
3. Missing Superuser flow to show this component
4. Hover/Click over badge to see badge info
5. API Calls
```javascript 
DELETE /badges
payload: {
id: string;
}
```

#### Small UI Features
- Hover over badge and on mobile-web click over badge to see description
- Badges component on member page vertical or horizontal scroll

## Dependencies
- Database
- Cloundinary
- Backend

## Alternatives Considered
- UI Design: No
- API Calls: In Progress

## Testing
- Test cases will be listed down for both frontend and backend 
  post UI design and API calls finalisization.

**Comment by shmbajaj** [comment]
`Update:`
- Delete or Remove badges is not part of feature.
- Title will be max 30 characters.
- Description will be max 30 characters.
- Assign/Unassign badges will be in two sections.
- Firebase firestore will have two collections one for badges and another for each badge assigned and each assign document will be created and on unassign document will be removed.
- To assign badges superuser will click on save button(placed on the header of the component).
- To add new badgess superuser will see a button placed on the bottom/footer of the component.

cc: @vinayak-trivedi @DashDeipayan

**Comment by shmbajaj** [comment]
# Status || Update
- Backend Setup Finished
