### ISSUE TITLE
[WIP]Create a /member/:id page that shows more details of every member

### ISSUE THREAD

**Issue by Harshi7016** [Real-Dev-Squad/website-members#49]

**Comment by Harshi7016** [comment]
Hi Team,
I would focus on creating a page to display the details of the user on click of image card,
I plan to display the details from data.json.
I would take the discussion to the Members-site-react for more details

**Comment by Harshi7016** [comment]
Hi Ankush, Nikhil's codepen view has met the requirements... I will assign him instead of me

**Comment by swarajpure** [comment]
I've been working on the backend, to get PRs of a particular user in RDS organization using GitHub APIs. I'm done with all the requested changes from my side, waiting for it to be reviewed.

**Comment by swarajpure** [comment]
Done
