### ISSUE TITLE
Migration to typescript

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-members#499]
# Issue:
Migrate members' site to typescript

**Description**
Currently, the members' site is written in javascript. We want to enforce types on the code for better development. Thus we want to migrate it to the migrate this site to TypeScript

**Comment by Dev-AkshatGupta** [comment]
Are we trying to migrate all of the types or specific component types.

### Suggestion 
If the types are migrated to this repo with a component-based approach it would be better to develop it that way (while folder structure has been discussed before for no confusion).

### Reasons(Behind Suggestion)-
-To migrate all types altogether needs a contract with the back-end. If we have those contracts we can go for it directly.
- It will help with name convention as it has to be named according to query and components.

Looking ahead to the conversation around this. Thanks :)

**Comment by RitikJaiswal75** [comment]
The site is being re-written so this issue is no more active
