### ISSUE TITLE
Members not showing up in doc loaded

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-members#53]
According to #50, We want to load the members from the server itself, and in the first HTML GET, have the content already present.

But it's not working currently. You can disable the JS on your browser and check. We should ideally see the members, with JS disabled on the browser.

![image](https://user-images.githubusercontent.com/1935403/89963776-2a240500-dc66-11ea-8b46-fecc5b30d8bf.png)

**Comment by ankushdharkar** [comment]
https://staging-members-rds.herokuapp.com/ has the main branch deployed always

**Comment by ankushdharkar** [comment]
This issue is still persisting with the images of the members:

![image](https://user-images.githubusercontent.com/1935403/91348235-1c8f8300-e801-11ea-871e-3df48a0dae7d.png)

**Comment by sumitd94** [comment]
#64 Fixed this bug
