### ISSUE TITLE
Remove cumulative layout shift on images loaded

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-members#54]
When the logo image loads, it pushes the members pictures down. Sometimes, the logo loads after the initial members load. If I am about to click a particular member, it will jump down by the time I click. This is not a great UX and needs to be addressed.

![cumulative layout shift for images](https://user-images.githubusercontent.com/1935403/89964515-fea21a00-dc67-11ea-80af-5a7817e2e019.gif)

Read more here: https://web.dev/cls/

**Comment by invalidtoken** [comment]
@ankushdharkar I can work on this issue.

**Comment by ankushdharkar** [comment]
@invalidtoken I think this is good for a first-timer to the repo. Let's leave it for them :)

**Comment by invalidtoken** [comment]
Okay cool, makes sense.
