### ISSUE TITLE
Task status filter API pass wrong parameter

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-members#540]
**Description:**
Passing old task status(status=active) parameter in the API. Currently, we are using new task parameters like AVAILABLE, IN_PROGESS, ASSIGNED, etc.

**Screenshot**
![image](https://github.com/Real-Dev-Squad/website-members/assets/70854507/afabc64f-16e8-470c-b309-3064810af120)

**Comment by shubhamjaintech** [comment]
@ankushdharkar 
A. can you please help resolve below questions?
1. Do Active task section on member site signifies all the available task of user OR it signifies in progress tasks of user?
Based on the meaning will change the api parameter.
2. Do we need to change section title from 'Active Tasks' -> 
Option 1: Keep it same
Option 2: Change it to something else i.e ToDo Task

Current Behaviour on Prod
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/03c67728-1c89-4f82-9f6a-ad5e9e07317b)

B. Can i take this task? If yes please assign it to me, ETA/breakdown already shared in new-task channel.

cc @sahsisunny 

Thank you.

**Comment by shubhamjaintech** [comment]
Lower Env Testing:
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/63d86d47-22fd-4917-9395-b11327ddb841)

Api parameter change and error msg change reflecting fine.

**Comment by shubhamjaintech** [comment]
Prod Testing: When flag is true
![image](https://github.com/Real-Dev-Squad/website-members/assets/22474104/ca289a67-c1be-4dc8-9434-598ef19f5aac)

Working fine
