### ISSUE TITLE
Deprecate the /members API in favor of /users

### ISSUE THREAD

**Issue by poornima-alugubelly** [Real-Dev-Squad/website-members#547]
### Things to do
- [ ] Replace `/members` API with `/users` API 
- [ ]  Make modifications to `/users` API if needed to achieve the same
- [ ] Add caching module to `/users` API
- [ ] Add a feature flag based on which we will decide to use user API or member API 

### Client repositories which need changes

Pages in which the replacements has to be done:
1. Dashboard-site
- [x] [Task assignment page](https://dashboard.realdevsquad.com/task/) will now consume the response of `/users` API as a list of users to show as suggestion while assigning a task
- [x] [Online Members Page](https://dashboard.realdevsquad.com/online-members/online-members) will now consume the response of `/users` API as a list of users to be shown as online members.

2. status-site 
- [x] [Availability-panel-page](https://status.realdevsquad.com/availability-panel) will now consume the `users/search?state=IDLE` API to show a list of users who are idle
3. members-site
- [ ] [Members-page](https://members.realdevsquad.com/)

**Comment by RitikJaiswal75** [comment]
Please take a look here as well @poornima-alugubelly 
https://github.com/Real-Dev-Squad/todo-action-items/issues/110

**Comment by RitikJaiswal75** [comment]
look in the linked and closed PRs here: https://github.com/Real-Dev-Squad/website-backend/issues/608

**Comment by prakashchoudhary07** [comment]
Closing this, as the changes are migrated to the new repo (https://github.com/Real-Dev-Squad/members-site/)
