### ISSUE TITLE
Component to hold each member in the all members view

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-members#7]
We need a component to hold the pic, name and social media icons of a member

Similar to:
https://www.ng-conf.org/speakers/
https://conf.reactjs.org/speakers.html
https://reactjsgirls.com/#speakers

**Comment by ankushdharkar** [comment]
@harshi7016 This is now yours. Please also assign it to yourself once you accept the invite to join the team.

**Comment by invalidtoken** [comment]
This is resolved by PR #19. Closing this issue.
